# Generated by Django 4.2.1 on 2023-05-07 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_auto_20230129_0553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='agent',
            new_name='agente',
        ),
    ]
