# Generated by Django 4.1.6 on 2023-09-18 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0012_estado_rename_is_organisor_user_gerente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estado',
            name='estado',
        ),
    ]
