# Generated by Django 4.1.6 on 2023-09-18 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0013_remove_estado_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='rol',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='leads.userprofile'),
            preserve_default=False,
        ),
    ]
