# Generated by Django 4.1.6 on 2023-09-18 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0014_agent_rol'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='rol',
            new_name='organisation',
        ),
        migrations.AddField(
            model_name='lead',
            name='organisation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='leads.userprofile'),
            preserve_default=False,
        ),
    ]
