# Generated by Django 4.2.1 on 2023-09-25 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0015_rename_rol_agent_organisation_lead_organisation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.FloatField()),
                ('stock', models.IntegerField()),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Proforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.BooleanField()),
                ('observacion', models.CharField(max_length=200)),
                ('pvp', models.FloatField()),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='vendedor',
            new_name='is_agent',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='gerente',
            new_name='is_organisor',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='cedula',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='email',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='fecha_ingreso',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='cedula',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='estado',
        ),
        migrations.DeleteModel(
            name='Estado',
        ),
        migrations.AddField(
            model_name='proforma',
            name='agente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.agent'),
        ),
        migrations.AddField(
            model_name='proforma',
            name='articulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.articulo'),
        ),
        migrations.AddField(
            model_name='proforma',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.lead'),
        ),
        migrations.AddField(
            model_name='lead',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='leads.category'),
        ),
    ]
