# Generated by Django 4.2.1 on 2023-09-26 08:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0016_articulo_category_proforma_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='date_added',
        ),
        migrations.AddField(
            model_name='agent',
            name='apellido',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agent',
            name='cedula',
            field=models.IntegerField(default='0'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agent',
            name='fecha_ingreso',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='agent',
            name='nombre',
            field=models.CharField(default='SinNombre', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agent',
            name='telefono',
            field=models.CharField(default='0999999999', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lead',
            name='cedula',
            field=models.IntegerField(default='0999999999'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lead',
            name='fecha_ingreso',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='proforma',
            name='fecha_ingreso',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
