# Generated by Django 4.2.1 on 2023-09-26 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0017_remove_lead_date_added_agent_apellido_agent_cedula_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='email',
            field=models.EmailField(default='correo', max_length=254),
            preserve_default=False,
        ),
    ]
