# Generated by Django 4.2.1 on 2023-10-03 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0020_proforma_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='proforma',
            name='tiempo',
            field=models.CharField(default='alquilerxhora', max_length=200, verbose_name='tiempo de alquiler'),
            preserve_default=False,
        ),
    ]
