# Generated by Django 4.2.1 on 2023-10-03 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0021_proforma_tiempo'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='direccion_domicilio',
            field=models.CharField(default='Direccion de domicilio', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lead',
            name='direccion_evento',
            field=models.CharField(default='Direccion de Evento', max_length=200),
            preserve_default=False,
        ),
    ]
